### ISSUE TITLE
After adding homekit, I can boot and control the volume normally, but... .

### ISSUE THREAD

**Issue by horseytr** [carlosgamezvillegas/homebridge-zidoo-androidtv#4]
I'm using `Ziddo NEOS`
And it's open in the plugin`Enable PowerOff mode instead of Standby Mode`
<img width="712" alt="iShot_2024-09-13_13 14 11" src="https://github.com/user-attachments/assets/784daabb-d227-49ad-b0a4-800fe9e31426">
After adding homekit, I can boot and control the volume normally, but **Every time I shut down in Homekit,NEOS did not shut down, the power display light was always on, and it did not work when I turned it on again.** 
How should I solve this problem, thank you!

**Comment by carlosgamezvillegas** [comment]
Hello @horseytr,

Unfortunately the plugin only supports the smart TV boxes from Zidoo. While I assume the NEOS uses a similar API as the TV boxes do, they might not be 100% the same and since I don’t own a NEOS it would be hard for me to find a solution to your problem. 

You, as an owner, could reach out to Zidoo to get the NEOS API and share it with me to find a solution.

Kind regards,
